version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - db