default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test